# Default Configuration for Live Scheduler

# =======================================================================================
# Client Settings
# =======================================================================================
client_mode: "mock"
mock_exposure_duration: 90
scl_server_ip: "observer4.ctio.noao.edu"
scl_server_port: 20000
propid: "2019A-0305"

# =======================================================================================
# UI Settings
# =======================================================================================
ui_mode: "cli"
show_plots: false

# =======================================================================================
# Model Settings
# =======================================================================================
model_path_or_alias: "mock"
device: "cpu"
field_choice_method: "interp"

# =======================================================================================
# Pathing
# =======================================================================================
field_lookup_dir: "./field_lookups"
fields_path: null
output_directory: "./observing_logs"
session_id: null

# =======================================================================================
# Operational Settings
# =======================================================================================
chunk_size: 3
min_chunk_size: null
observing_poll_rate_sec: 1
telemetry_poll_rate_sec: 20
seeing_window: "15m"

# =======================================================================================
# Observing Limits
# =======================================================================================
start_time: null
start_sun_elevation_deg: null
stop_time: null
stop_sun_elevation_deg: null
