experiment_name: max_feature_set_nside32
data:
  name: des-data-v0
  nside: 32
  action_space: azel_filter
  norm:
    feature_norm_mappings:
      ra:
      - cyclical
      az:
      - cyclical
      ha:
      - cyclical
      lst:
      - cyclical
      el:
      - z_score
      dec:
      - z_score
      sun_ra:
      - cyclical
      sun_az:
      - cyclical
      sun_el:
      - z_score
      sun_dec:
      - z_score
      moon_ra:
      - cyclical
      moon_az:
      - cyclical
      moon_el:
      - z_score
      moon_dec:
      - z_score
      moon_distance:
      - z_score
      sun_distance:
      - z_score
      airmass:
      - log
      - z_score
      sky_brightness:
      - z_score
      delta_az:
      - z_score
      delta_el:
      - z_score
      fwhm:
      - log
      - z_score
      urgency:
      - z_score
      pointing_distance:
      - z_score
      num_unvisited_fields:
      - z_score
      num_incomplete_fields:
      - z_score
      min_tiling:
      - z_score
      rel_num_unvisited_fields:
      - local_mean_z
      rel_num_incomplete_fields:
      - local_mean_z
      rel_min_tiling:
      - local_mean_z
      rel_moon_distance:
      - local_mean_z
      rel_ha:
      - local_mean_z
      rel_t_since_last_visit:
      - local_mean_z
      t_night:
      - fractional
      t_survey:
      - fractional
      moon_phase:
      - fractional
      survey_num_visits_done:
      - fractional
      t_until_set:
      - fractional
      t_since_last_visit:
      - z_score
      global_mean_tiling:
      - fractional
    fix_nans: true
  seeing:
    window: 15m
    retention_window: null
    from_instrument: 0.5
    to_instrument: 0.5
  state_dim: 38
  bin_state_dim: 50
  num_bins: 6080
  num_filters: 5
  num_actions: 30400
  global_features:
  - t_night
  - moon_distance
  - airmass
  - az
  - el
  - ha
  - lst
  - sun_ra
  - sun_dec
  - sun_az
  - sun_el
  - moon_ra
  - moon_dec
  - moon_el
  - moon_az
  - is_filter
  - sky_brightness
  - global_mean_tiling
  - fwhm
  bin_features:
  - ha
  - el
  - az
  - dec
  - airmass
  - sun_distance
  - moon_distance
  - rel_moon_distance
  - rel_ha
  - rel_min_tiling
  - rel_num_incomplete_fields
  - rel_num_unvisited_fields
  - rel_t_since_last_visit
  - min_tiling
  - num_incomplete_fields
  - num_unvisited_fields
  - delta_az
  - delta_el
  - pointing_distance
  - t_until_set
  start_date: '2013-01-01'
  end_date: '2019-01-31'
  years:
  - 2013
  - 2014
  - 2015
  - 2016
  - 2017
  - 2018
  - 2019
  months:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  days:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  - 18
  - 19
  - 20
  - 21
  - 22
  - 23
  - 24
  - 25
  - 26
  - 27
  - 28
  - 29
  - 30
  - 31
  filters:
  - g
  - r
  - i
  - z
  - Y
  train_nights: null
  val_nights:
  - '2015-10-19'
  - '2018-11-27'
  - '2015-09-07'
  - '2016-01-10'
  - '2015-12-13'
  - '2015-01-11'
  - '2018-09-10'
  - '2014-11-24'
  - '2017-12-23'
  - '2015-09-03'
  - '2018-12-13'
  - '2014-11-04'
  - '2018-11-26'
  - '2013-12-27'
  - '2018-12-17'
  - '2017-10-15'
  - '2016-12-04'
  - '2015-11-02'
  - '2018-10-27'
  - '2016-10-05'
  - '2016-02-12'
  - '2016-01-08'
  - '2015-10-22'
  - '2017-09-01'
  - '2015-10-08'
  - '2015-12-22'
  - '2015-08-22'
  - '2013-11-22'
  - '2018-12-04'
  - '2016-01-09'
  - '2014-09-19'
  - '2017-08-30'
  - '2014-09-24'
  - '2014-02-05'
  - '2017-01-26'
  - '2015-02-10'
  - '2015-01-12'
  - '2016-10-25'
  - '2015-08-15'
  - '2014-09-15'
  - '2015-08-21'
  - '2013-12-19'
  - '2016-02-10'
  - '2017-12-10'
  - '2018-10-18'
  - '2018-01-10'
  - '2018-11-28'
  - '2016-10-19'
  - '2013-12-23'
  - '2017-02-05'
  - '2015-10-04'
  - '2014-01-13'
  - '2016-10-28'
  - '2013-09-11'
  - '2013-12-08'
  - '2016-09-14'
  - '2017-11-09'
  - '2016-01-16'
  - '2018-11-14'
  - '2017-09-23'
  - '2013-10-14'
  - '2015-01-20'
  - '2018-01-19'
  - '2013-12-26'
  - '2018-02-05'
  - '2017-12-11'
  - '2015-01-10'
  - '2013-11-28'
  train_val_split: 0.9
model:
  network: contextual_score_mlp
  loss_strategy: pure_joint
  hidden_dim: 128
  nlayers: 3
  loss_function: cross_entropy
  contextual_gating: false
  activation: leaky_relu
  global_enc_dim: 128
  layernorm: true
  algorithm: bc
  reduction: mean
  gamma_focal: 2.0
  alpha: null
  filter_penalty: null
  alpha_bin: null
  beta_filter: null
  zeta_joint: null
  reward: null
  reward_weights:
    w_slew: 1.0
    w_airmass: 1.0
    w_t_last_visit: 1.0
    w_min_tiling: 1.0
    airmass_limit: 3.0
    t_ref_seconds: 43200.0
train:
  checkpoint_metric: val_loss
  max_epochs: 50
  batch_size: 1024
  lr_scheduler: cosine_annealing
  num_workers: 4
  lr_init: 0.001
  lr_final: 1.0e-06
  lr_sched_epoch_start: 10
  lr_sched_epoch_duration: 20
  patience: 20
  device: cuda
  seed: 42
  lr_scheduler_kwargs:
    T_max: 1680
    eta_min: 1.0e-06
device: cuda
